app:
  replicas: 1
  image: vikashashoke/ui
  env: qa
  computeres:
    limits:
      cpu: 0.5
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 1Gi

hpa:
  enabled: false
  maxReplicas: 10
  minReplicas: 4
  targetCPUUtilizationPercentage: 50ui-deploy/values-dev.yaml